# /.github/workflows/dockerHub.yml

name: DockerHub
on: push
jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Unit-tests
        run: echo tests soon
#       - name: Build with Maven
#         run: mvn clean compile package

  build-to-docker:
    needs: [tests]
    name: Push to docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean compile package
      - name: Build docker image
        working-directory: 'micro-products'
        run: docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/micro-products-workflow:test .
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/micro-products-workflow:test

  push-to-yandex:
    needs: [tests]
    name: Push to Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean compile package
      - name: Build docker image
        working-directory: 'api-gateway'
        run: docker build -f Dockerfile -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/egorov-api-gateway:test .
      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push tag to YC Registry
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/egorov-api-gateway:test

  deploy-gateway:
    needs: [ push-to-yandex ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/egorov-api-gateway:test
          revision-service-account-id: ${{ secrets.YC_SA_ID }}