# /.github/workflows/dockerHub.yml

name: DockerHub
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Push Docker Image
        uses: MathieuSoysal/jib-container-publish.yml@v2.1.4
        with:
          # Use docker.io for Docker Hub if empty
          REGISTRY: docker.io
          # github.repository as <your-account>/<your-repo>
          IMAGE_NAME: oviplok/MicroMarket-mirea/micro-products
          # Tag name of the image to publish
          tag-name: test
          # Username to login to registry
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          # Password to login to registry
          PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          java-version: 17

#  deploy:
#    needs: [build]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Build docker image
#        working-directory: ./micro-products
#        run: |
#          docker build micro-products --file micro-products/Dockerfile --tag micro-products:latest
#
#      - name: Log in to DockerHub
#        uses: docker/login-action@v3.0.0
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Push tag to DockerHub
#        run: |
#          docker push ${{ secrets.DOCKER_USERNAME }}/micro-products-workflow:latest
